import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/common/app-sidebar";
import Container from "@/components/common/container";

const InterSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InterSans.variable}  antialiased bg-dashboard-background text-clr-silver-v1`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="flex-1">
            <SidebarTrigger className="mt-2 ms-2 " />
            <Container>{children}</Container>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
