name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
        script: |
          # 1. Masuk ke folder repo jimpitan yang bener di VPS
          cd ~/jimpitan/jimpitan-frontend || exit
          git pull origin main

          # 2. Suntik file .env baru (yang ujungnya udah ada /api) ke folder yang bener
          echo "${{ secrets.ENV_FRONTEND }}" > .env

          # 3. Masuk ke folder utama jimpitan untuk nembak docker-compose yang bener
          cd ~/jimpitan
          docker compose down frontend
          docker compose build --no-cache frontend
          docker compose up -d frontend

          # 4. Bersihkan sisa-sisa image lama
          docker image prune -f
